version: '3'

x-spark-worker-common: &spark-worker-common
  image: bitnami/spark:3.5.5
  restart: on-failure
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
  command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - smart_city_network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - smart_city_network

  broker:
    image: confluentinc/cp-server:7.9.0
    container_name: broker
    restart: on-failure
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - smart_city_network

  spark-master:
    image: bitnami/spark:3.5.5
    container_name: spark_master
    restart: on-failure
    command: spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    networks:
      - smart_city_network

  spark-worker-1:
    container_name: spark-worker-1
    <<: *spark-worker-common

  spark-worker-2:
    container_name: spark-worker-2
    <<: *spark-worker-common

volumes:
  kafka_data:

networks:
  smart_city_network: